# Generated by Django 6.0.5 on 2026-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
