# Generated by Django 5.2.14 on 2026-06-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_response_is_accepted'),
        ('questions', '0004_profile'),
    ]

    operations = [
    ]
